version: '3'

services:
   db:
     image: mongo:latest
     command: mongod --storageEngine=wiredTiger
     volumes:
       - mongo_data:/data/db
     restart: always

   app:
     environment:
      - MONGO_URL=mongodb://brewportal_db_1:27017/meteor
      - ROOT_URL=http://localhost
     depends_on:
       - db
     image: psaleh/brew-portal
     ports:
       - "80:80"
     restart: always

volumes:
    mongo_data: